django-app/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from config import views

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^post/', include('post.urls')),
                  url(r'^member/', include('member.urls')),
                  url(r'^$', views.index, name='index'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-app/member/urls.py
from django.conf.urls import url

from . import views

app_name = 'member'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$',views.logout, name='logout'),
    url(r'^signup/$',views.signup, name='signup'),
]

django-app/post/urls.py
from django.conf.urls import url
from . import views

app_name = 'post'
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^.*/$', views.post_anyway, name='post_anyway'),
    # url(r'^(?P(<post_pk>\d+)/$',views.post_detail,name='post_detail'),
]

django-app/member/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

django-app/post/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    photo = models.ImageField(upload_to='post', blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_posts',
        through='PostLike',
    )
    tags = models.ManyToManyField(
        'Tag',
        blank=True,
    )

    class Meta:
        ordering=['-pk',]

    def add_comment(self, user, content):
        return self.comment_set.create(author=user, content=content)

    def add_tag(self, tag_name):
        tag, tag_created = Tag.objects.get_or_create(name=tag_name)
        if not self.tags.filter(name=tag_name).exists():
            self.tags.add(tag)

    @property
    def like_count(self):
        return self.like_users.count()


class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)


class PostLike(models.Model):
    post = models.ForeignKey(Post)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_date = models.DateTimeField(auto_now_add=True)

    # class Meta:
    #     db_table='post_post_like_users'


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return 'Tag ({})'.format(self.name)

django-app/member/forms.py
from django import forms
from django.contrib.auth import authenticate


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'placeholder': '사용자 아이디를 입력하세요'
            }
        )

    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'placeholder': '비밀번호를 입력하세요'
            }
        )
    )

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        user = authenticate(
            username=username,
            password=password,
        )
        if user is not None:
            self.cleaned_data['user'] = user
        else:
            raise forms.ValidationError(
                'login credentials not valid'
            )

django-app/config/views.py
from django.shortcuts import redirect


def index(request):
    return redirect('post:post_list')

django-app/member/views.py
from django.contrib.auth import authenticate, login as django_login, logout as django_logout, get_user_model
from django.http import HttpResponse
from django.shortcuts import render, redirect

from member.forms import LoginForm

User = get_user_model()

def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.cleaned_data['user']
            django_login(request,user)
            return redirect('post:post_list')
        else:
            return HttpResponse('Login credntails invalid')
    else:
        if request.user.is_authenticated:
            return redirect('post:post_list')

        form = LoginForm()
        context = {
            'form':form,
        }
        return render(request, 'member/login.html', context)


def logout(request):
    django_logout(request)
    return redirect('post:post_list')


def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if User.objects.filter(username=username).exists():
            return HttpResponse('Username exist')
        elif password1 != password2:
            return HttpResponse('password difference')
        user = User.objects.create_user(
            username=username,
            password=password2,
        )
        django_login(request,user)
        return redirect('post:post_list')
    else:
        return render(request, 'member/signup.html')

django-app/post/views.py
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.http import HttpResponseNotFound
from django.shortcuts import render, redirect

from .models import Post

User = get_user_model()


def post_list(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'post/post_list.html', context)


def post_detail(request, post_pk):
    try:
        post = Post.objects.get(pk=post_pk)
        context = {
            'post': post
        }

    except Post.DoesNotExist as e:
        # return HttpResponseNotFound('Post not found, detail:{}'.format(e))
        return redirect('post:post_list')

    return render(request, 'post/post_detail.html', context)


def post_create(request):
    if request.method == 'POST':
        user = User.objects.first()
        post = Post.objects.create(
            author=user,
            photo=request.FILES['file'],
        )
        comment_string = request.Post.get('comment', '')

        if comment_string:
            post.comment_set.create(
                author=user,
                content=comment_string,
            )

        return redirect('post:post_detail', post_pk=post.pk)
    else:
        return render(request, 'post/post_create.html')


def post_anyway(request):
    return redirect('post:post_list')

django-app/templates/common/base.html
{%load static%}
<!doctype html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Instagram-p</title>
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="{% static 'css/layout.css' %}">
  <link rel="stylesheet" href="{% static 'css/post.css' %}">
  <link rel="stylesheet" href="{% static 'css/common.css' %}">
</head>

<body>
  <div id="wrap">
    <header class="top-header">
      <nav>
        <div class="nav-left nav-item">
          <a href="">
            <img src="{%static 'image/logo.png'%}" alt="">
          </a>
        </div>

        <div class="nav-center nav-item">
          <input type="text" placeholder="검색">

        </div>

        <div class="nav-right nav-item">
          <a href="">
            <img src="{%static 'image/icon_explore.png'%}" alt="">
          </a>
          <a href="">
            <img src="{%static 'image/icon_heart.png'%}" alt="">
          </a>
          <a href="">
            <img src="{%static 'image/icon_profile.png'%}" alt="">
          </a>
        </div>

      </nav>
      <div>
        <nav>
          {% if user.is_authenticated %}
          <span>{{user}}로 로그인중</span>
          <a href="{%url 'member:logout'%}" class=".btn">Logout</a>
          {% else %}
          <a href="{%url 'member:login'%}" class=".btn">Login</a>
          {% endif %}
        </nav>
      </div>
    </header>
    <div class="test">
      <!-- {% if user.is_authenticated %}
            {{user}}이 로그인 중입니다
        {% else %}
            로그인하세요
        {% endif%} -->

    </div>


    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </div>
</body>

</html>

django-app/templates/include/post.html
<article class="post">
  <header>
    <div class="post-header-left">
    <img src="" alt="">
    <span>{{post.auth}}</span>
    </div>
    <div class="post-header-right">

    </div>
    </header>
    <div class="post-photo-container">

      {% if type == 'list'%}<a href="{% url 'post:post_detail' post_pk=post.pk %}">{%endif%}
      <img src="{{post.photo.url}}" alt="">
      {% if type == 'list'%}</a>{%endif%}
    </div>
    <div class="post-btn-container">
      <a href="#">
        <img src="" alt="">
      </a>
      <a href="#">
        <img src="" alt="">
      </a>
    </div>
    <p> 좋아요 {{post.like_count}} 개 </p>
    <div class="post-comment-container">
      {% for comment in post.comment_set.all%}
      <div class="post-comment">
        <span class="comment-author">{{comment.author}}</span>
        <span class="comment-content">
          <a href="" class="comment-author"></a>
          <span class="comment-content">{{comment.content}}</span>
          <a href="" class="comment-tag"></a>
          <!--<p class="comment-created">{{comment.created_date}}</p>-->
        </span>
      </div>
      {% endfor %}
    </div>
    <p class="create">{{post.created_date}}</p>
    <form action=" ">
      <input type="text" placeholder="댓글달기">
    </form>
</article>

django-app/templates/member/login.html
{%extends 'common/base.html'%}

{%block content%}

<div>
    <form action="" method="POST">
        {% csrf_token%}
        {{form}}
        <button type="submit">로그인!</button>
    </form>
</div>

{%endblock%}

django-app/templates/member/signup.html
{% extends 'common/base.html' %}

{%block content%}

<div>
    <form action="" method="POST">
        {%csrf_token%}
        <input type="text" name="username">
        <input type="password" name="password1">
        <input type="password" name="password2">
        <button type="submit">가입하기</button>
    </form>
</div>
{% endblock%}

django-app/templates/post/post_create.html
{%extends 'common/base.html'%}

{% block content %}
<div>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="file">
        <input type="text" name="comment" placeholder="댓글">
        <button tpye="submit">등록</button>
    </form>
</div>

{% endblock%}

django-app/templates/post/post_detail.html
{% extends 'common/base.html'%}
{%block content%}
    {% include 'include/post.html'%}

{%endblock%}

django-app/templates/post/post_list.html
{% extends 'common/base.html'%}
{%block content%}
{% for post in posts %}
    {%include 'include/post.html' with type='list'%}
{%endfor%}
{%endblock%}